dmlc/decord

- include/decord/base.h
- src/video/ffmpeg/ffmpeg_common.h
- src/video/storage_pool.h
- src/video/video_reader.cc
- Fixing #1 with various possible FFMPEG mem leaks.
- Disables thread local mem pool for now since fix is taking longer than I expected.
> Fix memleak

- src/video/ffmpeg/ffmpeg_common.h
- src/video/video_reader.cc
> fix end of file skipping method

- README.md
- cmake/util/FindFFmpeg.cmake
CMake is terrible at finding custom ffmpeg libs. This pr try to make things easier.
> Support -DFFMPEG_DIR in cmake

- python/decord/video_reader.py
- tests/python/unittests/test_video_reader.py
Very nice little library. Thought some syntax sugar wouldn't hurt.
> Add support for slicing in VideoReader

- README.md
- python/decord/bridge/__init__.py
- python/decord/bridge/torchdl.py
Just add bridge for pytorch. As pattern for mxnet. Data transformet to torch format: (Frames, Channels, H, W) and revers for in operation (tensor from F,C,H,W - > F,H,W,C )
Tested local for VideoReader
> Add bridge for pytorch

- README.md
- python/decord/bridge/__init__.py
- python/decord/bridge/tf.py
Adding tensorflow bridge. This should work with tf>=2.2.0 (only nightly right now).
> Add bridge for tensorflow

- README.md
> Deep learning framework bridge

- src/video/nvcodec/cuda_threaded_decoder.cc
- src/video/video_reader.cc
Fix https://github.com/dmlc/decord/issues/31
> Fix gpu decoding

- src/video/ffmpeg/threaded_decoder.cc
- src/video/ffmpeg/threaded_decoder.h
- src/video/nvcodec/cuda_decoder_impl.cc
- src/video/nvcodec/cuda_threaded_decoder.cc
- src/video/nvcodec/cuda_threaded_decoder.h
- src/video/threaded_decoder_interface.h
- src/video/video_reader.cc
Fix https://github.com/dmlc/decord/issues/39, https://github.com/dmlc/decord/issues/40, https://github.com/dmlc/decord/issues/31
> Refactor cuvid

- src/video/nvcodec/cuda_threaded_decoder.cc
- src/video/video_reader.cc
Fix a device_id issue that cause gpu id > 0 error
> fix multi-gpu

- src/video/nvcodec/cuda_threaded_decoder.cc
- src/video/nvcodec/cuda_threaded_decoder.h
> catch for cuda processing thread

- python/decord/__init__.py
- python/decord/bridge/__init__.py
- python/decord/bridge/mxnet.py
- python/decord/bridge/tvm.py
- tests/python/unittests/test_bridges.py
> add tvm bridge, add tests for bridges

- tests/python/unittests/test_video_reader.py
> fix unittests

- python/decord/bridge/__init__.py
- tests/python/unittests/test_bridges.py
Fix #85 Use bridge setting from main thread when new threads are launched.
> Fix #85 thread local bridge setting

- src/video/nvcodec/cuda_threaded_decoder.cc
- src/video/video_reader.cc
Fix https://github.com/dmlc/decord/issues/100, https://github.com/dmlc/decord/issues/102
> Fix cuda decoder and improve the robustness of seeking with frame based av_seek_frame

- src/video/video_reader.cc
For more details see https://github.com/dmlc/decord/issues/111
> revert frame based seeking due to speed regression

- python/decord/video_reader.py
This avoids double conversion in get_frame_timestamp(...)
> Change validate_indices to return numpy ndarray

- src/audio/audio_reader.cc
- src/video/video_reader.cc
- tests/python/unittests/test_video_reader.py
> EOF retry logic: add environment variable and instruction

- src/video/video_reader.cc
Add final seek attempt with frame based seeking.
> Fix #124 with more tolerant seek

- .github/workflows/pypi.yml
- src/audio/audio_reader.cc
- src/audio/audio_reader.h
- src/video/video_reader.cc
- src/video/video_reader.h
- tools/build_macos_10_9.sh
- tools/build_manylinux2010.sh
> fix assigning to 'AVCodec *' from incompatible type 'const AVCodec *'

- src/audio/audio_reader.cc
Output buffer was not freed. Also added free to couple other ptrs.
> fix mem leak
